#!/usr/bin/env python3
"""Assemble the self-contained HTML report for a research run.

Renders <run-dir>/report.md to <run-dir>/report.html and embeds the interactive
knowledge graph (graph.html) and any charts (charts/*.html) inline via iframes
(srcdoc), producing a single shareable file with no external dependencies.

Usage:
    python scripts/assemble_report.py --run-dir <RUN_DIR>
"""

from __future__ import annotations

import argparse
import html as _html
import re
from pathlib import Path

# markdown is optional; fall back to a minimal renderer if absent.
try:
    import markdown as _md  # type: ignore

    def md_to_html(text: str) -> str:
        return _md.markdown(text, extensions=["tables", "fenced_code", "toc"])
except Exception:  # noqa: BLE001
    def md_to_html(text: str) -> str:
        return _minimal_md(text)


PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  :root {{ --ink:#1d3557; --muted:#6b7785; --line:#e6e9ee; --accent:#457b9d; }}
  body {{ font-family: system-ui,-apple-system,Segoe UI,Roboto,sans-serif; color:var(--ink);
         max-width: 1000px; margin: 0 auto; padding: 32px 24px 80px; line-height:1.55; }}
  h1 {{ font-size: 1.8rem; margin-bottom:.2rem; }}
  h2 {{ margin-top: 2rem; padding-top:.6rem; border-top:1px solid var(--line); }}
  table {{ border-collapse: collapse; width:100%; margin:1rem 0; font-size:.92rem; }}
  th,td {{ border:1px solid var(--line); padding:6px 10px; text-align:left; }}
  th {{ background:#f5f7fa; }}
  code,pre {{ background:#f5f7fa; border-radius:4px; }}
  pre {{ padding:12px; overflow:auto; }}
  blockquote {{ border-left:4px solid var(--accent); margin:1rem 0; padding:.4rem 1rem;
               background:#f7fafc; color:var(--muted); }}
  .embed {{ border:1px solid var(--line); border-radius:8px; width:100%; }}
  .embed.graph {{ height: 820px; }}
  .embed.chart {{ height: 760px; }}
  .disclaimer {{ color:var(--muted); font-size:.82rem; margin-top:3rem; }}
</style></head>
<body>
{body}
</body></html>
"""


def _iframe(src_html: str, cls: str) -> str:
    return f'<iframe class="embed {cls}" srcdoc="{_html.escape(src_html, quote=True)}"></iframe>'


def _inject_embeds(body_html: str, run: Path) -> str:
    """Replace ```graph.html``` / ```charts/x.html``` references and known section
    markers with inline iframes of the generated interactive files."""
    embeds: list[tuple[str, str, str]] = []  # (anchor, file, css-class)

    graph = run / "graph.html"
    if graph.exists():
        embeds.append(("graph.html", str(graph), "graph"))
    charts_dir = run / "charts"
    if charts_dir.exists():
        for ch in sorted(charts_dir.glob("*.html")):
            embeds.append((f"charts/{ch.name}", str(ch), "chart"))

    for anchor, fpath, cls in embeds:
        frame = _iframe(Path(fpath).read_text(), cls)
        # Replace an explicit `Embed: charts/x.html` / inline-code mention if present,
        # otherwise append at the end under a heading.
        pattern = re.compile(
            rf"(<code>{re.escape(anchor)}</code>|Embed:\s*{re.escape(anchor)})"
        )
        if pattern.search(body_html):
            # function replacement so backslashes in the embedded HTML aren't
            # interpreted as regex replacement escapes (\d, \1, ...)
            body_html = pattern.sub(lambda _m: frame, body_html, count=1)
        else:
            body_html += f"\n<h2>{anchor}</h2>\n{frame}\n"
    return body_html


def render(run: Path) -> Path:
    md_path = run / "report.md"
    if not md_path.exists():
        raise SystemExit(f"report.md not found in {run}")
    text = md_path.read_text()
    title = next((ln.lstrip("# ").strip() for ln in text.splitlines()
                  if ln.startswith("#")), "Equity Research")
    body = md_to_html(text)
    body = _inject_embeds(body, run)
    if "Not investment advice" not in body:
        body += ('<p class="disclaimer">Generated by the equity-research '
                 "multi-agent skill. Data: Massive & Alpha Vantage. "
                 "Not investment advice.</p>")
    out = run / "report.html"
    out.write_text(PAGE.format(title=_html.escape(title), body=body))
    return out


def _minimal_md(text: str) -> str:
    """Tiny markdown fallback: headings, bold, tables, paragraphs."""
    lines = text.splitlines()
    out, in_table = [], False
    for ln in lines:
        if ln.startswith("#"):
            level = len(ln) - len(ln.lstrip("#"))
            out.append(f"<h{level}>{_html.escape(ln.lstrip('# ').strip())}</h{level}>")
        elif "|" in ln and ln.strip().startswith("|"):
            cells = [c.strip() for c in ln.strip().strip("|").split("|")]
            if set("".join(cells)) <= set("-: "):
                continue  # separator row
            tag = "td"
            if not in_table:
                out.append("<table>")
                in_table = True
                tag = "th"
            out.append("<tr>" + "".join(f"<{tag}>{_html.escape(c)}</{tag}>" for c in cells) + "</tr>")
        else:
            if in_table:
                out.append("</table>")
                in_table = False
            if ln.strip():
                out.append(f"<p>{_html.escape(ln)}</p>")
    if in_table:
        out.append("</table>")
    html = "\n".join(out)
    html = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", html)
    html = re.sub(r"`(.+?)`", r"<code>\1</code>", html)
    return html


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-dir", required=True)
    args = ap.parse_args()
    out = render(Path(args.run_dir))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
